# @package _global_
user: kao_user
dataset:
  train:
  - user: 99999999
    session: custom_train
  val:
  - user: 99999999
    session: custom_val
  test:
  - user: 99999999
    session: custom_test
