# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

band_rotation:
  _target_: emg2qwerty.transforms.ForEach  # i.i.d rotation offset for each band
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

duplicate_channel:
  _target_: emg2qwerty.transforms.ChannelDuplicator
  target_channels: 16  # Or whatever dimension you want to duplicate along

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 12  # Max 60ms jitter for 2kHz EMG

logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 10  # Downsamples from 200Hz to 20Hz

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 3  # Max 200ms per time mask for 125Hz spectrogram
  n_freq_masks: 3
  freq_mask_param: 6

transforms:
  train:
    - ${to_tensor}
    - ${duplicate_channel}
    - ${band_rotation}
    - ${temporal_jitter}
    - ${logspec}
    - ${specaug}

  val:
    - ${to_tensor}
    - ${duplicate_channel}
    - ${logspec}

  test: ${transforms.val}
